FROM node:20-alpine
WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/api/package.json ./apps/api/
RUN npm ci -w api --omit=dev && npm cache clean --force

COPY apps/api ./apps/api
WORKDIR /app/apps/api

ENV NODE_ENV=production
EXPOSE 6661
CMD ["npm", "run", "start"]
